version: '3.7'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=players
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
  players:
    build:
      dockerfile: app.Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/players
    ports:
      - 5000:5000
    depends_on:
      - db